.github/README.md
.github/ci-scripts/check-version-bump.sh
.github/ci-scripts/toggle-alpha.sh
.github/workflows/build-test-report.yml
.github/workflows/create-release.yml
.github/workflows/naming-conventions.yml
.github/workflows/prepare-release.yml
.gitignore
package.json

This pull request tests the release GHA jobs and fixes small requests from the apps team

ci: Release and some fixes

---

.github/workflows/create-release.yml
.github/workflows/naming-conventions.yml

Create a tag along with the release when coming into main

ci: Create a tag with the draft release

---

package.json

To releae the last PR as it was skipped from version bump

ci:  New pkg version: 0.0.0-alpha.3

---

package.json
src/IndexerQueries/assetSnapshots.ts
src/IndexerQueries/assetTransactions.ts
src/IndexerQueries/epochs.ts
src/IndexerQueries/index.ts
src/IndexerQueries/trancheCurrencyBalance.ts
src/Reports/Processor.test.ts
src/Reports/Processor.ts
src/Reports/Reports.test.ts
src/Reports/index.ts
src/tests/mocks/mockAssetTransactions.ts
src/tests/mocks/mockEpochs.ts
src/types/reports.ts

- adds orders report 
- adds assetTimeSeries report
- fixes failing test (subquery was reindexed and now there's more data for Base, so some of the numbers changed)
- added fields that we're missing in older report @kattylucy 
#44

feat: add orders report

---

package.json

feat: bump sdk version

---

package.json
src/IndexerQueries/assetTransactions.ts
src/IndexerQueries/poolFeeTransactions.ts
src/Reports/Processor.ts
src/types/reports.ts

- adds missing fields to assetTransaction report: name, principalAmount and interestAmount
- fixes null error in fee transaction

fix: report queries

---

package.json
src/tests/mocks/mockAssetTransactions.ts

fix: tests

---

package.json
src/IndexerQueries/assetSnapshots.ts
src/IndexerQueries/poolFeeTransactions.ts
src/IndexerQueries/trancheCurrencyBalance.ts
src/Reports/Processor.ts
src/Reports/Reports.test.ts
src/types/reports.ts
src/utils/BigInt.test.ts
src/utils/BigInt.ts
src/utils/decimal.ts

- tokenPrice report:  
-  add field `yieldSinceInception`
- assetList report:
- fix field `marketPrice`
- fix field `faceValue`
- feeTransaction report:
- fix field `feeId`
- add field `transactionType`
- balanceSheet report:
- fix field `trancheValue`
- fix field `totalCapital`
- investorList report:
- fix field `poolPercentage`

fix: add report missing fields and fix decimal arithmetic

---

src/Centrifuge.ts
src/tests/Centrifuge.test.ts
src/types/index.ts

Adds a global cache option, so users can disable caching when using the SDK in a script for example
Closes: #52

feat: Global cache option

---

src/Centrifuge.ts
src/config/protocol.ts
src/types/index.ts

- Retrieve pool data
- Set metadata method
#66

fix: type for protocol contracts

---

src/Centrifuge.test.ts
src/Centrifuge.ts
src/config/protocol.ts
src/entities/Pool.test.ts
src/entities/PoolNetwork.ts
src/entities/Vault.test.ts
src/types/index.ts
src/utils/types.test.ts
src/utils/types.ts

fix: types and errors

---

.github/workflows/build-test-report.yml
.github/workflows/create-release.yml
.github/workflows/naming-conventions.yml
package.json
src/Centrifuge.test.ts
src/Centrifuge.ts
src/config/chains.ts
src/entities/Pool.test.ts
src/entities/Pool.ts
src/tests/mocks/mockPoolMetadata.ts
src/types/index.ts
src/types/poolInput.ts
src/types/poolMetadata.ts
src/utils/createPinning.ts
src/utils/currencies.ts
src/utils/pinToApi.test.ts
src/utils/pinToApi.ts
src/utils/types.test.ts
src/utils/types.ts

- Retrieve pool data
- Update metadata
#66

feat: Retrieve pool data

---

src/entities/Pool.test.ts

fix: metadata test

---

src/Centrifuge.ts
src/entities/Reports/index.ts
src/entities/Vault.ts
src/types/query.ts

- Cleanup unsubscribed observables earlier
- use milliseconds for cache time to align with other config options
- update Vault investment functions

refactor: Change caching of observables

---

package.json
src/Centrifuge.test.ts
src/Centrifuge.ts
src/abi/Accounting.abi.ts
src/entities/Investor.ts
src/entities/Pool.test.ts
src/entities/Pool.ts
src/entities/ShareClass.test.ts
src/entities/ShareClass.ts
src/entities/Vault.ts
src/tests/mocks/mockPoolMetadata.ts
src/tests/setup.ts
src/types/index.ts
src/types/poolMetadata.ts

* Add indexer
* Query assets
* Query holdings
* Create holding
* Query pools
* Query whether account is manager
* Update manager
* Create account
* Query NAV per network
* Update NAV
#101 #74 #94 #95

feat: Pool manager functions

---

src/Centrifuge.test.ts
src/Centrifuge.ts
src/entities/Pool.ts
src/entities/ShareClass.ts
src/tests/mocks/mockPoolMetadata.ts
src/types/poolInput.ts
src/types/poolMetadata.ts
src/utils/index.ts
src/utils/types.ts

Create pool, in one multicall. Requires the signer to have auth on the Hub
#74

feat: Create pool

---

README.md
package.json

chore: Release

---

package.json
src/Centrifuge.ts
src/entities/ShareClass.test.ts
src/entities/ShareClass.ts
src/entities/Vault.test.ts

Get pending order amounts for all assets in a share class. Approve and/or issue for multiple assets at once.
#97 #100

feat: Pending amounts and batch approve/issue 

---

package.json
src/Centrifuge.ts
src/entities/Pool.test.ts

Fix centrifugeId being undefined for global assets

fix: Assets

---

package.json
src/Centrifuge.ts

fix: Assets return decimals

---

package.json
src/Centrifuge.ts
src/entities/ShareClass.ts

Fix asset id after indexer update

fix: Asset ID

---

package.json
src/Centrifuge.test.ts
src/Centrifuge.ts
src/entities/BalanceSheet.test.ts
src/entities/Pool.ts
src/entities/Vault.test.ts

- Fix pools query not being type Query
- Fix share classes details never resolving when there's no share classes
- Single query for all protocol addresses

fix: Pools query and other fixes

---

package.json
src/entities/PoolNetwork.ts

fix: Deploy vault

---

package.json
src/abi/AsyncRequestManager.abi.ts
src/entities/Vault.ts

uint256 to uint128
fix vault allowance
#156

fix: AsyncRequestManager abi

---

package.json
src/Centrifuge.ts
src/entities/ShareClass.ts

fix: Transaction titles and rpc url ranking

---

package.json
src/entities/ShareClass.ts

fix: Member

---

package.json
src/Centrifuge.ts
src/entities/PoolNetwork.ts
src/entities/ShareClass.ts
src/types/transaction.ts
src/utils/transaction.ts

Add VaultUpdateKind to the message data in `_estimate` to get the right gas estimate

fix: Update vault message types

---

package.json
src/entities/PoolNetwork.test.ts
src/entities/PoolNetwork.ts
src/entities/ShareClass.ts
src/entities/Vault.test.ts
src/entities/Vault.ts

Return only linked vaults by default. provide option to return unlinked vaults as well

feat: Filter unlinked vaults

---

package.json
src/Centrifuge.ts

fix: Assets query

---

package.json
src/entities/ShareClass.ts

feat: Share class deployment per network

---

package.json
src/entities/Vault.ts

fix: Investing with smart contract wallet

---

package.json
src/Centrifuge.ts

fix: Retry message

---

src/entities/OnOffRampManager.test.ts
src/entities/OnOffRampManager.ts

fix: transactions

---

package.json
src/entities/Investor.test.ts
src/entities/Investor.ts
src/entities/ShareClass.test.ts
src/entities/ShareClass.ts
src/utils/BigInt.ts

- Retrieve members of a given share class

feat: retrieve members of a share class

---

package.json
src/entities/OnOffRampManager.test.ts
src/entities/OnOffRampManager.ts
src/entities/PoolNetwork.test.ts

- Ability to disbled (delete) relayers.

feat: ability to disable relayers

---

package.json
src/entities/Vault.ts

fix: Redeem check
